/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tu_jnilog_clog_CLog */

#ifndef _Included_com_tu_jnilog_clog_CLog
#define _Included_com_tu_jnilog_clog_CLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tu_jnilog_clog_CLog
 * Method:    i
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tu_jnilog_clog_CLog_i
  (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
